/*
 * ECE 461 - Fall 2021 - Project 2
 *
 * API for ECE 461/Fall 2021/Project 2: A Trustworthy Module Registry
 *
 * API version: 2.0.0
 * Contact: davisjam@purdue.edu
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"CreateAuthToken",
		strings.ToUpper("Put"),
		"/authenticate",
		CreateAuthToken,
	},

	Route{
		"PackageByNameDelete",
		strings.ToUpper("Delete"),
		"/package/byName/{name}",
		PackageByNameDelete,
	},

	Route{
		"PackageByNameGet",
		strings.ToUpper("Get"),
		"/package/byName/{name}",
		PackageByNameGet,
	},

	Route{
		"PackageCreate",
		strings.ToUpper("Post"),
		"/package",
		PackageCreate,
	},

	Route{
		"PackageDelete",
		strings.ToUpper("Delete"),
		"/package/{id}",
		PackageDelete,
	},

	Route{
		"PackageRate",
		strings.ToUpper("Get"),
		"/package/{id}/rate",
		PackageRate,
	},

	Route{
		"PackageRetrieve",
		strings.ToUpper("Get"),
		"/package/{id}",
		PackageRetrieve,
	},

	Route{
		"PackageUpdate",
		strings.ToUpper("Put"),
		"/package/{id}",
		PackageUpdate,
	},

	Route{
		"PackagesList",
		strings.ToUpper("Post"),
		"/packages",
		PackagesList,
	},

	Route{
		"RegistryReset",
		strings.ToUpper("Delete"),
		"/reset",
		RegistryReset,
	},
}
