/*
 * ECE 461 - Spring 2023 - Project 2
 *
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * API version: 2.0.0
 * Contact: davisjam@purdue.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	log "github.com/sirupsen/logrus"
	"os"
	sw "github.com/mabaums/ece461-web/backend/openapi"
)

func main() {
	log.SetLevel(log.DebugLevel)
	log.SetOutput(os.Stderr)
	log.Info("Server started")

	router := sw.NewRouter()

	log.Fatal(router.Run(":8000"))
}
