/*
 * ECE 461 - Fall 2021 - Project 2
 *
 * API for ECE 461/Fall 2021/Project 2: A Trustworthy Module Registry
 *
 * API version: 2.0.0
 * Contact: davisjam@purdue.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateAuthToken -
func CreateAuthToken(c *gin.Context) {
	c.JSON(http.StatusOK, "string")
}

// PackageByNameDelete - Delete all versions of this package.
func PackageByNameDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PackageByNameGet -
func PackageByNameGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PackageCreate -
func PackageCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PackageDelete - Delete this version of the package.
func PackageDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PackageRate -
func PackageRate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PackageRetrieve -
func PackageRetrieve(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PackageUpdate - Update this version of the package.
func PackageUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PackagesList - Get packages
func PackagesList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// RegistryReset -
func RegistryReset(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
