#!/bin/bash

if [ "$1" == "install" ]; then
    go get app/git
    go get app/github
    go get app/lg
    go get app/npm
elif [ "$1" == "test" ]; then
    go test ./... -coverprofile=coverage.out ./... -v > /dev/null 2>&1
    go tool cover -func=coverage.out > coverage.txt
    bash parse.sh < coverage.out
    rm -r coverage.out
    rm -r coverage.txt
    find git/ -name log_file.txt -delete
    find github/ -name log_file.txt -delete
    find npm/ -name log_file.txt -delete
elif [ "$1" == "build" ]; then
    go build
elif [ -f "$1" ]; then
    go run Main.go $1 

else
    echo "Invalid argument. Usage: ./run [install|test|URL_FILE.txt]"
fi
