/*
 * ECE 461 - Spring 2023 - Project 2
 *
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * API version: 2.3.1
 * Contact: davisjam@purdue.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// PackageRegEx -
type PackageRegEx struct {

	// A regular expression over package names and READMEs that is used for searching for a package
	RegEx string `json:"RegEx"`
}
