/*
 * ECE 461 - Spring 2023 - Project 2
 *
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * API version: 2.3.1
 * Contact: davisjam@purdue.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// User -
type User struct {

	//
	Name string `json:"name"`

	// Is this user an admin?
	IsAdmin bool `json:"isAdmin"`
}
